### PR TITLE
Improved ImageMagick feed

### PR DESCRIPTION
**Pull request by bastianeicher**
Improved ImageMagick feed

- Fixed icon URLs
- Replaced interface URI with `<feed-for>` in template
- Replace bundled ffmpeg for 64-bit builds as well (for consistency)
- Removed download links to imagemagick.org, because archives there get removed as soon as a new version is released
- Set stability to stable
- Added more versions
- Tweaked formatting

### CODE REVIEW

**Comment by pmiess** [comment]
The ffmpeg dependency is necesary because the bundled one is not the correct bitness

if you remove the ftp.icm.edu.pl feeds then feed is gone as soon as the new one is released.

**Comment by pmiess** [comment]
The template lost the URI and gained the feed-for element but the feed did not

**Comment by bastianeicher** [comment]
> The ffmpeg dependency is necesary because the bundled one is not the correct bitness

Oh, that's an interesting bug. :D Thanks for pointing that out. I've now gone the other way and modified the feed to replace ffmpeg for both 32-bit and 64-bit implementations, for consistency and to allow users to pick a specific version of ffmpeg if the want.

> if you remove the ftp.icm.edu.pl feeds then feed is gone as soon as the nest version is released.
> imagemagick.org doesnt keep any history

Good point. I've modified the feed and watch script to only use `ftp.icm.edu.pl`. That will prevent problems with 0install potentially giving up if the first archive URI points to a missing archive. Also, this way the watch script can pick up multiple new versions if it hasn't been run in a while.

> The template lost the URI and gained the feed-for element but the feed did not

That is intended. An `.xml.template` is used to generate a "partial" feed, that contains only a single version of an application - and therefore does not contain the `uri` attribute. 0repo then uses the URI in the `<feed-for>` element to determine the "full" feed it is supposed to be merged into.

**Comment by bastianeicher** [comment]
Included in #162

**Pull request closed without merging**
