### PR TITLE
Update ffmpeg

### PR DESCRIPTION
**Pull request by bastianeicher**

### CODE REVIEW

**Comment by talex5** [comment]
```
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=00cd6377e6075236933ef75b273ac38f56748304' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=00cd6377e6075236933ef75b273ac38f56748304' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=00cd6377e6075236933ef75b273ac38f56748304' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
```

**Comment by bastianeicher** [comment]
Whoops, I forgot to remove the ID from the template file causing it to be the same for all new versions. Fixed now.

**Comment by talex5** [comment]
It still seems to contain duplicates, though not as many:
```
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
WARNING:0install:Duplicate ID 'sha1new=315460953b8552b661ae03fcd18a140b61996a64' in feed '<Feed http://repo.roscidus.com/utils/ffmpeg>'
```

**Comment by bastianeicher** [comment]
Sorry for the hassle. :(
One more attempt.

**Pull request merged**
