### PR TITLE
Add missing sub-feeds to Python

### PR DESCRIPTION
**Pull request by talex5**
The Python feed now imports the new feed at apps.0install.net, which imports platform-specific sub-feeds. However, `<feed>` isn't recursive so this doesn't work. Instead, import these feeds directly.

/cc @bastianeicher

### CODE REVIEW

**Comment by bastianeicher** [comment]
Did the same for the Git, Go, Helm, PowerShell and Java feeds.

**Comment by talex5** [comment]
Thanks! Are you going to push to the public repo, or shall I do that?

**Comment by bastianeicher** [comment]
Would be great if you could do that.

`0install run http://0install.net/tools/0repo.xml` isn't working on Windows at the moment. Haven't look into what's wrong. Hoping 0install/0install-feeds#4 will resolve it.

**Comment by talex5** [comment]
Done. It has created lots of empty catalog.xml files now!

**Pull request merged**
