### PR TITLE
add netcdf

### PR DESCRIPTION
**Pull request by pmiess**
netcdf is a dependency for gnuwin32 GRI package.

This appears to the the last user contrib zip file on their server.

support for https://github.com/0install/0install.de-feeds/issues/3

### CODE REVIEW

**Comment by pmiess** [comment]
@bastianeicher would it be useful to change the run_tests command to the default command test listed in the 0install Feed enditor pulldown menu for command name?

**Comment by bastianeicher** [comment]
The command name `test` is used by the [0test](http://0install.net/0test.html), so changing it seems like a good idea.

**Comment by talex5** [comment]
```
Feed 'feeds/lib/netcdf.xml' declares uri='https://repo.roscidus.com/lib/netcdf',
which is not under REPOSITORY_BASE_URL (http://repo.roscidus.com/)
```

Trying to use https gives:

```
repo.roscidus.com uses an invalid security certificate.
The certificate is only valid for sunjammer.sugarlabs.org
```

So we should probably stick to http for now (and rely on the GPG signatures).

**Comment by pmiess** [comment]
feed updated to use http

**Pull request merged**
