### PR TITLE
Added helm-autoversion

### PR DESCRIPTION
**Pull request by bastianeicher**
Helm Autoversion is a small Python wrapper for Kubernetes Helm that automatically downloads a Helm (client) version that matches the Tiller (server) version.

This PR requires [helm-autoversion.zip](https://github.com/0install/repo.roscidus.com/files/3395714/helm-autoversion.zip) to be placed in `incoming/`. This ZIP file contains the same `helm-autoversion.py` file that is also included in the PR for reference.

Suggested update for `kubernetes/index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>repo.roscidus.com: Kubernetes</title>
  </head>
  <body>
    <h1>repo.roscidus.com: Kubernetes</h1>
    <p>
      Kubernetes is an open source system for managing containerized applications across multiple hosts.
    </p>

    <p>To add the Kubernetes client CLI to your <code>PATH</code>:</p>
    <pre>
      $ 0install add kubectl http://repo.roscidus.com/kubernetes/kubectl
    </pre>

    <p>To add additional common Kubernetes tools to your <code>PATH</code>:</p>
    <pre>
      $ 0install add minikube http://repo.roscidus.com/kubernetes/minikube
      $ 0install add helm http://repo.roscidus.com/kubernetes/helm
    </pre>

    <p>To make 0install automatically download a Helm (client) version that matches the Tiller (server) version:</p>
    <pre>
      $ 0install add helm http://repo.roscidus.com/kubernetes/helm-autoversion
    </pre>

    <p>To have 0install automatically pick Helm versions when pulled in as a dependency (e.g., from helmfile):</p>
    <pre>
      $ 0install add-feed http://repo.roscidus.com/kubernetes/helm-autoversion
    </pre>

    <h2>Official tools</h2>

    <ul>
      <li><a href='kubectl'>kubectl</a></li>
      <li><a href='minikube'>Minikube</a></li>
      <li><a href='helm'>Helm</a></li>
      <li><a href='kompose'>Kompose</a></li>
      <li><a href='kops'>kops</a></li>
      <li><a href='svcat'>svcat</a></li>
    </ul>

    <h2>3rd party tools</h2>

    <ul>
      <li><a href='helm-autoversion'>helm-autoversion</a></li>
      <li><a href='helmfile'>helmfile</a></li>
      <li><a href='k9s'>k9s</a></li>
    </ul>
  </body>
</html>
```

### CODE REVIEW

**Comment by talex5** [comment]
It seems a bit odd that you ask for one version of helm and get a different one, but only if the feed has been added. What about just making this a separate interface? i.e. the user installs it with:

```
$ 0install add helm http://repo.roscidus.com/kubernetes/helm-autoversion
```

**Comment by bastianeicher** [comment]
If a user specifies a specific version with `--version` that will still work, despite having called `0install add ...`. I like to think of it as "making 0install Helm-aware". By adding this feed the 0install selection behavior when specifying no version number simply changes from "latest stable Helm" to "the right version of Helm matching your server instance.

Also, registering helm-autoversion as an additional feed for helm makes it work for other tools that pull in helm as a `<executable-in-path>` dependency, such as helmfile, which would ignore an 0install app-alias.

**Comment by bastianeicher** [comment]
I've updated the HTML above to describe both possible usages.

**Comment by bastianeicher** [comment]
@talex5: Could you add this block to `kubernetes/index.html`?

```html
    <p>To make 0install automatically download a Helm (client) version that matches the Tiller (server) version:</p>
    <pre>
      $ 0install add helm http://repo.roscidus.com/kubernetes/helm-autoversion
    </pre>

    <p>To have 0install automatically pick Helm versions when pulled in as a dependency (e.g., from helmfile):</p>
    <pre>
      $ 0install add-feed http://repo.roscidus.com/kubernetes/helm-autoversion
    </pre>
```

**Comment by talex5** [comment]
Oops - fixed!

**Pull request merged**
