### PR TITLE
Moved .NET feeds and added .NET Core

### PR DESCRIPTION
**Pull request by bastianeicher**
Renamed and moved some feeds (avoids ambiguous and/or uncommon abbreviations `cli` and `netfx`):

| Old | New |
|-----|-----|
| http://repo.roscidus.com/cli/cli | http://repo.roscidus.com/dotnet/clr |
| http://repo.roscidus.com/cli/cli-monopath | http://repo.roscidus.com/dotnet/clr-monopath |
| http://repo.roscidus.com/cli/netfx | http://repo.roscidus.com/dotnet/framework |
| http://repo.roscidus.com/cli/netfx-client | http://repo.roscidus.com/dotnet/framework-client-profile |
| http://repo.roscidus.com/cli/mono | http://repo.roscidus.com/dotnet/mono |
| http://repo.roscidus.com/cli/ironpython | http://repo.roscidus.com/dotnet/ironpython |
| http://repo.roscidus.com/cli/nant | http://repo.roscidus.com/dotnet/nant |

Added `<feed src="..."/>` and `<replaced-by interface="..."/>` to the old feeds to forward to the new ones.

Added feeds for .NET Core.

### CODE REVIEW

**Comment by bastianeicher** [comment]
I have created a new [index.html](https://github.com/0install/repo.roscidus.com/files/1279240/dotnet-index.txt) file for http://repo.roscidus.com/dotnet/

**Comment by talex5** [comment]
I merged this but I see we now get:

```
WARNING:0install:Duplicate ID 'sha1new=522b80fb208e3e29cd6cfadfa894ed358892ea13' in feed '<Feed http://repo.roscidus.com/dotnet/core>'
```

**Comment by talex5** [comment]
I guess the main index needs updating too?

**Comment by bastianeicher** [comment]
Oops, I messed up one of the download links. Created #37 to fix that.

Yes, on the main index you can replace:
```html
<a href="cli/">Common Language Infrastructure</a> (.NET Framework and Mono)</li>
```
with:
```html
<a href="dotnet/">.NET</a> (.NET Core, .NET Framework and Mono)</li>
```

Thanks for all the merging work. :)

**Comment by talex5** [comment]
Done - thanks!

**Pull request merged**
