### PR TITLE
 add Gentoo packages for python-gobject 

### PR DESCRIPTION
**Pull request by pmiess**
add python gobject system packages for Gentoo

### CODE REVIEW

**Comment by talex5** [comment]
Squashed and merged - thanks!

**Comment by talex5** [comment]
I think the problem is that with

```xml
    <package-implementation distributions="Gentoo" package="dev-python/pygobject">
      <version not-before="3"/>
    </package-implementation>
```

`<version>` is not allowed here and is ignored. Therefore, both `<package-implementation>` elements expand to both implementations.

It does sound like a useful feature to have, though.

**Comment by pmiess** [comment]
The Arch package-implementation has this child element also, 
I see 2 paths forward here.
I could remove the version child elements and push the gentoo package implementation out of the v2/v3 groups or we could implement support for the version  child elements.
Please let me know if you would like me to implement option one.

**Comment by talex5** [comment]
Yes, probably best to move it for now.

**Pull request closed without merging**
