### PR TITLE
Added GitExtensions, PuTTY and FileZilla

### PR DESCRIPTION
**Pull request by bastianeicher**
For `git/index.html`:
```html
      <li><a href='gitextensions'>GitExtensions</a> (graphical interface for Git)</li>
```

For `utils/index.html`:
```html
      <li><a href='putty'>PuTTY</a> (Telnet and SSH client)</li>
      <li><a href='filezilla'>FileZilla</a> (cross-platform FTP, FTPS and SFTP client)</li>
```

### CODE REVIEW

**Comment by talex5** [comment]
```
Missing entry for FileZilla-config.zip.
```

Should `<archive href="FileZilla-config.zip"` be `<archive href="http://0install.de/files/hosted/FileZilla-config.zip"`?

**Comment by bastianeicher** [comment]
Right, forgot about that, sorry.

Maybe you could download http://0install.de/files/hosted/FileZilla-config.zip and host it on repo.roscidus.com so that everything is in one place?

The archive contains a single file, `fzdefaults.xml`, which disables FileZilla's built-in update check, since this would try to overwrite the contents of the read-only implementation cache.

**Comment by talex5** [comment]
```
Checking http://downloads.sourceforge.net/filezilla/FileZilla_3.10.1_win32.zip... ERROR
HTTP error: got status code 404 for http://downloads.sourceforge.net/filezilla/FileZilla_3.10.1_win32.zip
```

Looks like they've moved to a new location.

**Comment by bastianeicher** [comment]
Indeed! The files are now hosted on the project's own server (`download.filezilla-project.org`) instead of SourceForge. I've modified the feed accordingly and added some new versions.

I've also renamed `FileZilla-config.zip` to `filezilla.config.zip` and added it to the Git repo.

**Comment by talex5** [comment]
Thanks!

**Pull request merged**
