### PR TITLE
update expat  add gentoo package and cross distro package names add f…

### PR DESCRIPTION
**Pull request by pmiess**
add reference to windows feed for expat introduced in 
https://github.com/0install/0install.de-feeds/pull/24

also add Gentoo package name and cross distro package name expat

### CODE REVIEW

**Comment by bastianeicher** [comment]
Hi @pmiess,

what do you think about adding the Windows implementation directly to this feed, rather than introducing a new feed (http://0install.de/feeds/expat.xml)?

Regards
Bastian

**Comment by pmiess** [comment]
I thought that in comment https://github.com/0install/0install.de-feeds/issues/3#issuecomment-450849896 @talex5  indicated he didn't like that plan.

**Comment by bastianeicher** [comment]
As a rough guideline:
- http://repo.roscidus.com/ mostly contains open-source, cross-platform tools and libraries.
- http://0install.de/feeds/ contains some Windows-only and some non-FOSS freeware tools.

For example http://repo.roscidus.com/editors/vs-code contains Windows and Linux builds of Visual Studio Code.

Since libexpat is FOSS (MIT) and there is already a feed for it on repo.roscidus.com, I think Windows builds would fit in fine.

**Comment by pmiess** [comment]
I've added a pull request for your suggestion as #143 . Either one is fine with me.

**Comment by talex5** [comment]
(closing in favour of #143)

**Pull request closed without merging**
