### PR TITLE
Imported and extended HTML pages

### PR DESCRIPTION
**Pull request by bastianeicher**
I have imported the HTML pages served at http://repo.roscidus.com/ into Git and extended them.

My goal is to provide users a hierarchical view of the feeds available in the repository instead of the flat catalog view.

### CODE REVIEW

**Comment by talex5** [comment]
I think having a README.md in this repository is a good idea, but I'm not keen on the index files. It turns 0repo into a web-authoring system, which can have limitless complexity. What about having these files in this repository's wiki, for example?

**Comment by bastianeicher** [comment]
My intention was not really for the index files to be managed by 0repo but rather to just store them in the repository to allow change tracking and pull requests while still manually deploying the files to server which, as I assume, is what you already to for files like http://repo.roscidus.com/java/index.html.

Placing these files in the Wiki would mean formatting them as Markdown and only viewing them from within GitHub, right? My thinking was that, since repo.roscidus.com is more hierarchically structured than  most other feed repos, a set of manually index files deployed right alongside the files would be more useful for discovery than the auto-generated catalog.

**Comment by bastianeicher** [comment]
Independently of the question where to track/version these files, would you consider publishing the HTML files on http://repo.roscidus.com/ ?

This would make the new infrastructure feeds easier to discover.

**Comment by bastianeicher** [comment]
Sorry for warming this up again, but:

http://repo.roscidus.com/ has some static HTML files right now. These are somewhat outdated and incomplete.

Would you consider replacing/extending them with the ones from this pull request (whilst not necessarily tracking them in Git)?

The intention is simply to make some of the more basic "infrastructure" feeds easier to discover.

**Comment by talex5** [comment]
I've added the README and pushed the index files manually for now (it's actually another Git repository, but not public - mainly to avoid confusion).

Perhaps we should auto-generate the index for each directory with all the feeds in that directory, and just take a summary from the feeds directory.

I also removed the OCaml index, as that was only really an experiment and never updated. Possibly the feed should be removed from the feeds directory, so 0repo doesn't track it either and removes it from the catalogue.

**Comment by bastianeicher** [comment]
Thanks. :)

Yes, auto-generated an index for each dir with the summary snippet coming from a `description.md` or `description.html.partial` per directory sounds like a good idea to me too.

**Pull request closed without merging**
