### PR TITLE
Added Minikube, Kompose, kops and Go, updated various feeds

### PR DESCRIPTION
**Pull request by bastianeicher**
The following files need to be downloaded and placed into the `incoming` directory before running `0repo`:
- [docker-18.03.0-ce-win-x86_64.zip](https://github.com/0install/repo.roscidus.com/files/1904288/docker-18.03.0-ce-win-x86_64.zip)
- [docker-18.03.0-ce-linux-x86_64.tar.gz](https://github.com/0install/repo.roscidus.com/files/1904289/docker-18.03.0-ce-linux-x86_64.tar.gz)

Here is an updated `kubernetes/index.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>repo.roscidus.com: Kubernetes</title>
  </head>
  <body>
    <h1>repo.roscidus.com: Kubernetes</h1>
    <p>
      Kubernetes is an open source system for managing containerized applications across multiple hosts.
    </p>

    <p>To add the Kubernetes client CLI to your <code>PATH</code>:</p>
    <pre>
      $ 0alias kubectl http://repo.roscidus.com/kubernetes/kubectl
    </pre>

    <p>To add additional common Kubernetes tools to your <code>PATH</code>:</p>
    <pre>
      $ 0alias minikube http://repo.roscidus.com/kubernetes/minikube
      $ 0alias helm http://repo.roscidus.com/kubernetes/helm
      $ 0alias kompose http://repo.roscidus.com/kubernetes/kompose
    </pre>

    <h2>Available feeds</h2>

    <ul>
      <li><a href='kubectl'>kubectl</a></li>
      <li><a href='minikube'>Minikube</a></li>
      <li><a href='helm'>Kubernetes Helm</a></li>
      <li><a href='kompose'>Kompose</a></li>
      <li><a href='kops'>Kubernetes Operations (kops)</a></li>
    </ul>
  </body>
</html>
```

Here is an `index.html` for the new `golang/` directory:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>repo.roscidus.com: Go Programming Language</title>
  </head>
  <body>
    <h1>repo.roscidus.com: Go Programming Language</h1>
    <p>
      Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
    </p>

    <p>To add Go-related commands to your <code>PATH</code>:</p>
    <pre>
      $ 0alias go http://repo.roscidus.com/golang/go
      $ 0alias godoc http://repo.roscidus.com/golang/go godoc
      $ 0alias gofmt http://repo.roscidus.com/golang/go gofmt
    </pre>

    <h2>Available feeds</h2>

    <ul>
      <li><a href='go'>Go</a></li>
    </ul>
  </body>
</html>
```

### CODE REVIEW

**Comment by talex5** [comment]
Where did the docker archives come from?

Also: `Feed 'feeds/golang/go.xml' with uri='http://repo.roscidus.com/kubernetes/kubectl' should be located at 'feeds/kubernetes/kubectl.xml'`

**Comment by bastianeicher** [comment]
Docker unfortunately stopped publishing standalone builds of the client CLI on https://download.docker.com/. Therefore I created these two archives myself by:
- Installing [Docker for Windows](https://store.docker.com/editions/community/docker-ce-desktop-windows) and placing `C:\Program Files\Docker\Docker\resources\bin\docker.exe` in a ZIP archive.
- Copying `/usr/bin/docker` from the [`docker` image from the Docker Hub](https://hub.docker.com/_/docker/) and placing it in a TAR.GZ archive.

Sorry for the copy+paste mistake in the Go feed. I now fixed the `uri` attribute in `golang/go.xml`.

**Comment by talex5** [comment]
I tried the go one, and it fails with:

```
info: Download 'https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz' completed successfully (119914627 bytes)
info: Will run: tar --version
info: Will run: tar -xf /tmp/0install-8ce3ff-download -C /home/user/.cache/0install.net/implementations/0install-unpack-1905c57f --no-same-owner --no-same-permissions -z go
info: Removing temporary directory '/home/user/.cache/0install.net/implementations/tmp-37127d5e'
Incorrect manifest -- archive is corrupted.
Required digest: sha256new_NBVXBHLWVZMZETLREYGKLCH7JRGEYFR7VGZWSI3I5AD624C37X3Q
Actual digest: sha256new_H7V44FHDS7LE7EOMX3E5UGFEVRCMRYEXTRIXXZKAVPSD3IHYJGWA
... downloading implementation http://repo.roscidus.com/golang/go 1.10.1 (id=sha1new=6814a78b987fc49f76a1ab90a80e18accb53f8c9)
```

```
$ 0install store manifest go sha256new
[...]
F a9bdf01730d77197ae5dfcdf07fb7c136b48c15d5294f555f170757d3de6d27b 1522297741 300 semi4.go
F 121dcc0686e840f6dba42854b0c2d403db799faebb9d3867b93559ad6777e930 1522297741 262 semi5.go
F c8875c4baa89f9fdf0bc8191b2c6f018426f2ceb2ab00073370453e81ed9a2b5 1522297741 307 semi6.go
F 6a44e0d0cf9e0dbdd16dc14a9663e9ae180984edc89dcc455a232ac7bfab794e 1522297741 329 semi7.go
F 5bcb87b2caa0a63b903e4cb4c318b5599c291dd4fa944dc84298a30aa59bac44 1522297741 502 topexpr.go
F 636347365908b9c83ba95931637b41106fa3f6c7c527758753e9f62e57dac44e 1522297741 295 typesw.go
F ec94d54dab799c51b86394b848c3e04494c86b1b37f76d335c4663f737fda93d 1522297741 313 vareq.go
F e2268f8ef2fe3f5a1546c2fe5024807f655ea36ec1a5945508e8c97e0ed84c65 1522297741 361 vareq1.go
D /test/uintptrescapes.dir
F ecce4c074de9145c107940ed76ba03f2823add41b1970ed16dbfb63efe58f8c5 1522297741 879 a.go
F b090eeec8ae6d269a0785daec87091def645c4514df89ce4789263b6a422ccfc 1522297741 1314 main.go
sha256new_H7V44FHDS7LE7EOMX3E5UGFEVRCMRYEXTRIXXZKAVPSD3IHYJGWA
```

**Comment by talex5** [comment]
The kubectl one also fails:

```
Extract attribute may not contain / or \ (got 'kubernetes/client/bin')
... unpacking archive 'https://dl.k8s.io/v1.10.1/kubernetes-client-linux-amd64.tar.gz'
... downloading implementation http://repo.roscidus.com/kubernetes/kubectl 1.10.1 (id=sha1new=579a61b2eb7250b5589f113d4a24cfa7fddcd5cf)
```

Have these been tested?

**Comment by talex5** [comment]
compose and machine also failed to run:

```
Incorrect manifest -- archive is corrupted.                                                                              
Required digest: sha256new_ZURU6C3QWBSLEJWICDAQF7M6W3L24QEJA63HZTC6QSTK2AZKANUA
Actual digest: sha256new_VQXOKHHMEHIAIDAEEPZLESVG3AJP3FMBQKJVYYUD3B3UXTU7KI4Q
... downloading implementation http://repo.roscidus.com/docker/compose 1.21.0 (id=sha1new=744e7361df82b5dd49eb5cee49413cf582a64358)
```

```
execve(/home/user/.cache/0install.net/implementations/sha256new_CC4UVH3JZAR4MHKELLWI2DLOCGGDZGKQCDVA7IVFKIU6B5GQU37A/docker-machine): Permission denied
... trying to exec: /home/user/.cache/0install.net/implementations/sha256new_CC4UVH3JZAR4MHKELLWI2DLOCGGDZGKQCDVA7IVFKIU6B5GQU37A/docker-machine
... running http://repo.roscidus.com/docker/machine
````

Maybe I should revert this PR?

**Comment by bastianeicher** [comment]
These apps are published as single files rather than archives and need to be set as executable after download. I handled this using the `<file executable="true" .. />` syntax we discussed on the mailing list a while ago and documented in 0install/web-site#1. I forgot to follow up on implementing that in the OCaml version of Zero Install so it's currently only supported in the .NET version.

**Comment by bastianeicher** [comment]
Regarding the kubectl feed: I did not know the `extract` attribute was not allowed to specify sub-folders (did not see anything about that in the feed spec), so I implemented the .NET version to support that. I only tested that feed on Windows. I'll modify the kubectl feed to use `extract="kubernetes"` instead of `extract="kubernetes/client/bin"` and create a new PR for that.

**Comment by talex5** [comment]
Good point about `extract`. I've updated the feed spec to mention this (<http://0install.net/interface-spec.html#retrieval-methods>).

**Pull request merged**
